### ISSUE TITLE
inject with constructor

### ISSUE THREAD

**Issue by devmondo** [mench/dependency-injection-es6#1]
Hi,
can we add the `@inject` decorator on constructor of the class instead of on a property?

thanks in advanced.

**Comment by mench** [comment]
Hi thanks for your feedback.  
It can be done but I think it will cause contradiction issue with dependency injection pattern

**Comment by devmondo** [comment]
thanks for the prompt reply,

many frameworks do it
https://github.com/lgvo/di-decorators
https://github.com/aurelia/dependency-injection

i like yours because it is really small code :)

**Comment by mench** [comment]
Ok I agree with you :) I will add this feature and will update it soon. Thanks a lot.

**Comment by devmondo** [comment]
hahaha, thank you man, i did not mean to push it :)

**Comment by devmondo** [comment]
working perfectly thank you :)
